# Generated by Django 3.1.7 on 2021-04-08 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('olympiads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='olympiad',
            name='olympiad_round',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='olympiad_round', to='olympiads.olympiadround'),
        ),
        migrations.AlterField(
            model_name='olympiad',
            name='olympiad_round_not_real',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='olympiads.olympiadround'),
        ),
        migrations.AlterField(
            model_name='olympiad',
            name='olympiad_round_not_real_time_end',
            field=models.DateTimeField(default=None, null=True, verbose_name='Конец заочного тура'),
        ),
        migrations.AlterField(
            model_name='olympiad',
            name='olympiad_round_not_real_time_start',
            field=models.DateTimeField(default=None, null=True, verbose_name='Начало заочного тура'),
        ),
        migrations.AlterField(
            model_name='olympiad',
            name='olympiad_round_time_end',
            field=models.DateTimeField(null=True, verbose_name='Конец очного тура'),
        ),
    ]
