# Generated by Django 3.1.7 on 2021-04-08 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('olympiads', '0003_auto_20210408_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='olympiad',
            name='olympiad_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='olympiads.olympiadlevel', verbose_name='Уровень проведения олимпиады'),
        ),
    ]
