# Generated by Django 3.1.7 on 2021-04-18 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympiads', '0008_auto_20210408_1708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='olympiad',
            name='olympiad_level_id',
        ),
        migrations.RemoveField(
            model_name='olympiad',
            name='olympiad_round',
        ),
        migrations.RemoveField(
            model_name='olympiad',
            name='olympiad_round_not_real',
        ),
        migrations.RemoveField(
            model_name='olympiad',
            name='olympiad_round_not_real_time_end',
        ),
        migrations.RemoveField(
            model_name='olympiad',
            name='olympiad_round_not_real_time_start',
        ),
        migrations.RemoveField(
            model_name='olympiad',
            name='olympiad_round_time_end',
        ),
        migrations.RemoveField(
            model_name='olympiad',
            name='olympiad_round_time_start',
        ),
        migrations.AddField(
            model_name='olympiad',
            name='olympiad_extramural_round_end',
            field=models.DateTimeField(blank=True, default=None, verbose_name='Конец заочного тура', null=True),
        ),
        migrations.AddField(
            model_name='olympiad',
            name='olympiad_extramural_round_start',
            field=models.DateTimeField(blank=True, default=None, verbose_name='Начало заочного тура', null=True),
        ),
        migrations.AddField(
            model_name='olympiad',
            name='olympiad_intramural_end',
            field=models.DateTimeField(blank=True, default=None, verbose_name='Конец очного тура', null=True),
        ),
        migrations.AddField(
            model_name='olympiad',
            name='olympiad_intramural_start',
            field=models.DateTimeField(blank=True, default=None, verbose_name='Начало очного тура', null=True),
        ),
        migrations.AddField(
            model_name='olympiad',
            name='olympiad_level',
            field=models.CharField(choices=[('В', 'Всероссийский'), ('М', 'Межрегиональный'), ('Р', 'Региональный'), ('Г', 'Городской'), ('Ш', 'Школьный')], default='Ш', max_length=1, verbose_name='Уровень проведения олимпиады'),
        ),
        migrations.DeleteModel(
            name='OlympiadLevel',
        ),
        migrations.DeleteModel(
            name='OlympiadRound',
        ),
    ]
