# Generated by Django 3.1.7 on 2021-04-19 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olympiads', '0009_auto_20210418_1722'),
    ]

    operations = [
        migrations.RenameField(
            model_name='olympiad',
            old_name='olympiad_extramural_round_end',
            new_name='olympiad_extramural_end',
        ),
        migrations.RenameField(
            model_name='olympiad',
            old_name='olympiad_extramural_round_start',
            new_name='olympiad_extramural_start',
        ),
    ]
