# Generated by Django 3.1.7 on 2021-04-23 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympiads', '0012_olympiad_olympiad_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='olympiad',
            name='olympiad_extramural_end',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Конец заочного тура'),
        ),
        migrations.AlterField(
            model_name='olympiad',
            name='olympiad_extramural_start',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Начало заочного тура'),
        ),
        migrations.AlterField(
            model_name='olympiad',
            name='olympiad_intramural_end',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Конец очного тура'),
        ),
        migrations.AlterField(
            model_name='olympiad',
            name='olympiad_intramural_start',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Начало очного тура'),
        ),
    ]
