# Generated by Django 3.1.7 on 2021-04-25 08:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('olympiads', '0013_auto_20210423_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='olympiad',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='_olympiad_participants_+', to=settings.AUTH_USER_MODEL, verbose_name='Участники'),
        ),
        migrations.AddField(
            model_name='olympiad',
            name='winner',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Победитель'),
        ),
        migrations.AlterField(
            model_name='olympiad',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Название олимпиады'),
        ),
        migrations.AlterField(
            model_name='olympiad',
            name='olympiad_file',
            field=models.FileField(blank=True, null=True, upload_to='static/model_files/'),
        ),
        migrations.AlterField(
            model_name='olympiad',
            name='olympiad_level',
            field=models.CharField(choices=[('В', 'Всероссийская'), ('М', 'Межрегиональная'), ('Р', 'Региональная'), ('Г', 'Городскоая'), ('Ш', 'Школьная')], default='Ш', max_length=1, verbose_name='Уровень проведения олимпиады'),
        ),
    ]
