# Generated by Django 3.2.4 on 2021-06-23 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olympiads', '0017_auto_20210622_1912'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Olympiad',
        ),
    ]
