# Generated by Django 3.2.4 on 2021-06-23 13:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('olympiads', '0018_delete_olympiad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Olympiad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Название олимпиады')),
                ('olympiad_level', models.CharField(choices=[('Всероссийская', 'Всероссийская'), ('Межрегиональная', 'Межрегиональная'), ('Региональная', 'Региональная'), ('Городская', 'Городская'), ('Школьная', 'Школьная')], default='Школьная', max_length=20, verbose_name='Уровень проведения олимпиады')),
                ('olympiad_extramural_start', models.DateField(blank=True, default=None, null=True, verbose_name='Начало заочного тура')),
                ('olympiad_extramural_end', models.DateField(blank=True, default=None, null=True, verbose_name='Конец заочного тура')),
                ('olympiad_intramural_start', models.DateField(blank=True, default=None, null=True, verbose_name='Начало очного тура')),
                ('olympiad_intramural_end', models.DateField(blank=True, default=None, null=True, verbose_name='Конец очного тура')),
                ('olympiad_url', models.CharField(blank='false', default='Ссылка не найдена =(', max_length=60, verbose_name='Ссылка на сайт олимпиады')),
                ('olympiad_file', models.FileField(blank=True, null=True, upload_to='static/model_files/')),
                ('participants', models.ManyToManyField(blank=True, related_name='_olympiads_olympiad_participants_+', to=settings.AUTH_USER_MODEL, verbose_name='Участники')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='olympiads.olympiadsubject', verbose_name='Предмет')),
                ('winner', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Победитель')),
            ],
        ),
    ]
