# Generated by Django 3.1.7 on 2021-04-21 17:38

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Москва', max_length=50, verbose_name='Населённый пункт')),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Название учебного заведения')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_users.city', verbose_name='Населённый пункт')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(choices=[('M', 'Мужской'), ('Ж', 'Женский')], default='М', max_length=1, verbose_name='Пол')),
                ('third_name', models.CharField(max_length=30, verbose_name='Отчество')),
                ('grade', models.CharField(choices=[('1', 'Первый класс'), ('2', 'Второй класс'), ('3', 'Третий класс'), ('4', 'Четвёртый класс'), ('5', 'Пятый класс'), ('6', 'Шестой класс'), ('7', 'Седьмой класс'), ('8', 'Восьмой класс'), ('9', 'Девятый класс'), ('10', 'Десятый класс'), ('11', 'Одиннадцатый класс'), ('У', 'Учитель')], default='1', max_length=2, verbose_name='Класс обучения')),
                ('age', models.PositiveSmallIntegerField(default=7, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(4)], verbose_name='Возраст')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_users.school', verbose_name='Учебное заведение')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
