# Generated by Django 3.1.7 on 2021-04-22 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympiads', '0011_auto_20210419_1658'),
        ('app_users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='interest',
            field=models.ManyToManyField(to='olympiads.OlympiadSubject', verbose_name='Интересующие предметы'),
        ),
    ]
