# Generated by Django 3.1.7 on 2021-04-28 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0004_school_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='personal_data',
            field=models.BooleanField(default=True, verbose_name='Галочка на согласие о работе с персональными данными'),
        ),
    ]
