# Generated by Django 3.1.7 on 2021-06-22 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0005_profile_personal_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name_plural': 'Cities'},
        ),
        migrations.AddField(
            model_name='profile',
            name='send_emails',
            field=models.BooleanField(default=True, verbose_name='Согласие на получение email'),
        ),
    ]
